<?php
/**
 * @file
 * This is the main module file.
 */

/**
* Implementation of hook_menu().
*/
function attend_event_menu() {
  $items['attentevent'] = array(
    'title' => 'Attend Event',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('attend_event_form'),
    'access callback' => TRUE,
    );
  return $items;
}

function attend_event_form($form,&$form_submit) {
  $form['firstname'] = array(
    '#type' => 'textfield',
  );
  $form['firstname']['#attributes']['placeholder'] = 'Firstname';
  $form['lastname'] = array(
    '#type' => 'textfield',
  );
  $form['lastname']['#attributes']['placeholder'] = 'Lastname';
  $form['email']=array(
	'#type'=>'textfield',
  );
  $form['email']['#attributes']['placeholder'] = 'Email address(optional)';
  $form['submit'] = array(
    '#value' => 'Submit details',
    '#type' => 'submit',
    );
  return $form;
}

function attend_event_form_validate($form, $form_state) {

  if(empty($form_state['values']['firstname']))
     form_set_error('firstname','Firstname cannot be empty');
  else if(empty($form_state['values']['lastname']))
     form_set_error('lastname','Lastname cannot be empty');
  else if(filter_var($form_state['values']['email'], FILTER_VALIDATE_EMAIL) == false)
    form_set_error('email','Email address is not valid');
}

function attend_event_form_submit($form, $form_state) {
	$to      = 'ankita.sharma@byteclues.com';
	$subject = 'Attend Event';
	$message = 'Want to attend event';
	$headers = 'From: ' . $form['email']['#value'] . "\r\n" .
		"MIME-Version: 1.0\r\n" .
		"Content-type: text/html\r\n";

	$result = mail($to, $subject, $message, $headers);
	if($result==true){
		drupal_set_message("Your request has been sent.");
	} else {
		drupal_set_message("Please check your internet connection.");
	}
}

