<?php
/**
 * @file
 * This is the main module file.
 */

/**
* Implementation of hook_menu().
*/
function search_event_menu() {
  $items['searchevent'] = array(
    'title' => 'Search Event',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('search_event_form'),
    'access callback' => TRUE,
    );
  return $items;
}

function search_event_form($form,&$form_submit) {
	$form['location']=array(
        '#type'=>'select',
        '#options'=>array('Location or Institution','USA','UK','France','Japan')
    );
	$form['from_date']=array(
        '#type'=>'textfield',
    );
	$form['from_date']['#attributes']['placeholder'] = 'From Date';
	$form['to_date']=array(
        '#type'=>'textfield',
    );
	$form['to_date']['#attributes']['placeholder'] = 'To Date';
	$form['submit'] = array(
		'#value' => 'Search Events',
		'#type' => 'submit',
    );
  return $form;
}

function search_event_form_validate($form, $form_state) {
  if($form_state['values']['location']==0)
     form_set_error('location','Choose location');
  else if($form_state['values']['from_date']==0)
     form_set_error('from_date','Select from date');
  else if($form_state['values']['to_date']==0)
     form_set_error('to_date','Select to date');
}

function search_event_form_submit($form, $form_state) {
	drupal_set_message("Form submitted successfully.");
}

